name: CI for Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      # Prepare Allure history directory
      - name: Prepare Allure history
        run: mkdir -p allure-results

      # Run Playwright tests
      - name: Run Playwright tests
        run: |
          python -m pytest --alluredir=allure-results ./tests/step_defs/test_main_page_bdd.py -n 2
        continue-on-error: true 

      # Check Allure results (ensure test results exist)
      - name: Check Allure results
        if: always()
        run: |
          test -d allure-results && [ "$(ls -A allure-results)" ] || echo "No test results found"

      # Load test report history
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      # Build Allure report
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results  # Fixed path
          keep_reports: 5

      # Deploy Allure report to GitHub Pages
      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
