name: CI for Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
    contents: read
    actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium
      - name: Prepare Allure history
        run: |
          mkdir -p allure-results

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Playwright tests
        run: |
          python -m pytest --alluredir=allure-results ./tests/step_defs/test_main_page_bdd.py -n 2
        continue-on-error: true 

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results
          keep_reports: 5

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
          deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          publish_branch: gh-pages
          publish_dir: allure-history