name: CI for Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install --with-deps chromium

      # Run tests
      - name: Run Playwright tests
        run: |
          python -m pytest --alluredir=allure-results ./tests/step_defs/test_main_page_bdd.py -n 2
        continue-on-error: true 

      # Optionally push Allure results to an artifact
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
     
      - name: Display test logs
        run: cat allure-results/*.json
